[tool.poetry]
name = "slack-channel-munger"
version = "0.1.0"
description = ""
authors = ["Oliver Steele <steele@osteele.com>"]

[tool.poetry.scripts]
my-script = "slack_channel_munger:main"

[tool.poetry.dependencies]
python = "^3.8"
slack-sdk = "^3.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
